import './Course.css'
import Button from '../Button/Button'
import CodeDisplay from '../CodeDisplay/CodeDisplay'


function Course() {
    return (
        <div className="course" overflow="">
            <h1>Course</h1>
            <CodeDisplay />
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam?</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam et veritatis magni quis ea. Sapiente vero, quo deserunt facere a voluptatem. Qui odit dolores eum voluptates nihil cupiditate asperiores. Nobis.Lorem Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime architecto nulla sapiente? Ipsum neque vel quas minima reiciendis, enim quis quae odio! Totam dolorum fugiat ab. Tenetur illum eum neque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores officiis inventore, ea necessitatibus beatae cum perspiciatis animi sint? Nulla eos vero maxime cum velit dolore earum aperiam deserunt vel? Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum enim numquam porro distinctio? Fugiat delectus aut nam. Labore unde aut quod eaque, enim distinctio! Illum, maiores aut! Eius, dolore? Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim animi quibusdam soluta natus molestiae sit numquam excepturi magnam dolorem dignissimos provident iste aliquid sint vero, vel veniam ut? Quis, aperiam? </p>
            
            <Button next={false} />
            <Button next={true} />
        </div>
    )
}

export default Course